name = "KNITRO"
uuid = "67920dd8-b58e-52a8-8622-53c4cffbe346"
authors = ["Artelys", "jump-dev"]
version = "0.14.8"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[weakdeps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[extensions]
KNITROMathOptInterfaceExt = ["MathOptInterface"]

[compat]
Dates = "1.11.0"
Libdl = "1"
MathOptInterface = "1.17"
Printf = "1"
Random = "1.11.0"
SparseArrays = "1"
Test = "1"
julia = "1.9"

[extras]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["MathOptInterface", "Printf", "SparseArrays", "Test"]
