name: MINLPTests
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: KNITRO
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: '1'
          arch: 'x64'
      - uses: julia-actions/cache@v1
      - shell: bash
        env:
          SECRET_KNITRO_LICENSE: ${{ secrets.KNITRO_LICENSE }}
        run: |
          echo "$SECRET_KNITRO_LICENSE" > ~/artelys_lic.txt
      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: "Install pip"
        run: |
          python -m pip install --upgrade pip
      - name: "run_minlptests"
        env:
          KNITRO_JL_WHL: "true"
          SECRET_KNITRO_URL: ${{ secrets.KNITRO_URL }}
          SECRET_KNITRO_LIBIOMP5: ${{ secrets.KNITRO_LIBIOMP5 }}
        shell: julia --color=yes {0}
        run: |
          path = joinpath(ENV["GITHUB_WORKSPACE"], "test", "MINLPTests")
          cd(path)
          using Pkg
          Pkg.activate(".")
          Pkg.instantiate()
          Pkg.add(PackageSpec(path=ENV["GITHUB_WORKSPACE"]))
          Pkg.build("KNITRO")
          include(joinpath(path, "run_minlptests.jl"))
